spring:
  devtools:
    livereload:
      enabled: true

  h2:
    console:
      enabled: true

  jpa:
    database: h2
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:h2:mem:spring-tips;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
    driver-class-name: org.h2.Driver

  banner:
    location: classpath:banner/local.txt

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/config/mybatis-config.xml
